#include "gspl_sprites/channel_map.hpp"

#include <array>
#include <iostream>
#include <stdexcept>

using namespace gspl::sprites;
namespace{void check(bool value,const char*message){if(!value)throw std::runtime_error(message);}FrameSource target(){return{"idle.south.body.0000",{2,1,ColorSpace::srgb,AlphaMode::straight,{255,0,0,255,0,0,0,0}},1,1,3};}ChannelMap scalar(ChannelMapKind kind,std::uint8_t first,std::uint8_t second){return{"idle.south.body.0000."+std::to_string(static_cast<int>(kind)),"idle.south.body.0000",kind,{2,1,ColorSpace::data,AlphaMode::opaque,{first,first,first,255,second,second,second,255}}};}}

int main(){try{const auto frame=target();auto depth=scalar(ChannelMapKind::depth,0,255);auto effects=scalar(ChannelMapKind::effects,64,192);auto collision=scalar(ChannelMapKind::collision,0,255);ChannelMap material{"idle.south.body.0000.material","idle.south.body.0000",ChannelMapKind::material_id,{2,1,ColorSpace::data,AlphaMode::opaque,{1,0,0,255,2,0,0,255}}};ChannelMap normal{"idle.south.body.0000.normal","idle.south.body.0000",ChannelMapKind::tangent_normal,{2,1,ColorSpace::data,AlphaMode::opaque,{128,128,255,255,128,128,255,255}}};ChannelMap emissive{"idle.south.body.0000.emissive","idle.south.body.0000",ChannelMapKind::emissive,{2,1,ColorSpace::srgb,AlphaMode::opaque,{255,64,0,255,0,0,0,255}}};const std::array maps{depth,effects,collision,material,normal,emissive};for(const auto&map:maps)check(validate_channel_map(map,frame).ok(),"valid channel map rejected");const auto canonical=canonicalize_channel_maps(maps);check(canonical.find("gspl.sprite-channel-maps/0.1")!=std::string::npos&&canonical.find("material_id")<canonical.find("tangent_normal")&&canonical.find("tangent_normal")<canonical.find("depth"),"channel-map canonicalization failed");
  auto fractional=collision;fractional.image.pixels[0]=127;fractional.image.pixels[1]=127;fractional.image.pixels[2]=127;check(!validate_channel_map(fractional,frame).ok(),"fractional collision mask accepted");auto bad_normal=normal;bad_normal.image.pixels[2]=0;check(!validate_channel_map(bad_normal,frame).ok(),"inward or non-unit normal accepted");auto wrong_space=depth;wrong_space.image.color_space=ColorSpace::srgb;check(!validate_channel_map(wrong_space,frame).ok(),"data map with color semantics accepted");auto wrong_size=depth;wrong_size.image={1,1,ColorSpace::data,AlphaMode::opaque,{0,0,0,255}};check(!validate_channel_map(wrong_size,frame).ok(),"misaligned map dimensions accepted");bool duplicate=false;try{const std::array duplicates{depth,depth};(void)canonicalize_channel_maps(duplicates);}catch(const std::invalid_argument&){duplicate=true;}check(duplicate,"duplicate channel-map kind accepted for frame");std::cout<<"all gspl sprites channel-map tests passed\n";return 0;}catch(const std::exception&error){std::cerr<<error.what()<<'\n';return 1;}}
