#include "gspl_sprites/visual_set.hpp"

#include <algorithm>
#include <array>
#include <charconv>
#include <fstream>
#include <iomanip>
#include <limits>
#include <map>
#include <numeric>
#include <set>
#include <sstream>
#include <stdexcept>
#include <tuple>

namespace gspl::sprites {
namespace {
std::string trim(std::string value){const auto first=value.find_first_not_of(" \t\r\n");if(first==std::string::npos)return{};return value.substr(first,value.find_last_not_of(" \t\r\n")-first+1);}
std::vector<std::string> split(std::string_view value,char delimiter){std::vector<std::string> result;std::size_t start=0;while(start<=value.size()){const auto end=value.find(delimiter,start);result.emplace_back(value.substr(start,end==std::string_view::npos?value.size()-start:end-start));if(end==std::string_view::npos)break;start=end+1;}return result;}
std::uint32_t u32(std::string_view value,std::string_view field){std::uint32_t output{};const auto[end,error]=std::from_chars(value.data(),value.data()+value.size(),output);if(error!=std::errc{}||end!=value.data()+value.size())throw std::runtime_error("invalid unsigned integer for "+std::string(field));return output;}
std::int32_t i32(std::string_view value,std::string_view field){std::int32_t output{};const auto[end,error]=std::from_chars(value.data(),value.data()+value.size(),output);if(error!=std::errc{}||end!=value.data()+value.size())throw std::runtime_error("invalid signed integer for "+std::string(field));return output;}
bool boolean(std::string_view value,std::string_view field){if(value=="true")return true;if(value=="false")return false;throw std::runtime_error("invalid boolean for "+std::string(field));}
bool token(std::string_view value){return!value.empty()&&value.size()<=64&&std::ranges::all_of(value,[](unsigned char c){return(c>='a'&&c<='z')||(c>='0'&&c<='9')||c=='_'||c=='-';});}
Direction2d parse_direction(std::string_view value){static const std::map<std::string_view,Direction2d> values{{"none",Direction2d::none},{"north",Direction2d::north},{"north_east",Direction2d::north_east},{"east",Direction2d::east},{"south_east",Direction2d::south_east},{"south",Direction2d::south},{"south_west",Direction2d::south_west},{"west",Direction2d::west},{"north_west",Direction2d::north_west}};const auto found=values.find(value);if(found==values.end())throw std::runtime_error("invalid frame direction");return found->second;}
std::string_view direction_text(Direction2d value){static constexpr std::array values{"none","north","north_east","east","south_east","south","south_west","west","north_west"};return values.at(static_cast<std::size_t>(value));}
ChannelMapKind parse_map_kind(std::string_view value){static const std::map<std::string_view,ChannelMapKind> values{{"material_id",ChannelMapKind::material_id},{"tangent_normal",ChannelMapKind::tangent_normal},{"depth",ChannelMapKind::depth},{"emissive",ChannelMapKind::emissive},{"effects",ChannelMapKind::effects},{"collision",ChannelMapKind::collision}};const auto found=values.find(value);if(found==values.end())throw std::runtime_error("invalid channel-map kind");return found->second;}
std::string_view map_kind_text(ChannelMapKind value){static constexpr std::array values{"material_id","tangent_normal","depth","emissive","effects","collision"};return values.at(static_cast<std::size_t>(value));}
bool safe_path(std::string_view value){if(value.empty()||value.size()>1024||value.front()=='/'||value.back()=='/'||value.find('\\')!=std::string_view::npos||value.find(':')!=std::string_view::npos||!std::ranges::all_of(value,[](unsigned char c){return c>=0x20&&c<0x7f;}))return false;std::size_t start=0;while(start<value.size()){const auto end=value.find('/',start);const auto part=value.substr(start,end==std::string_view::npos?value.size()-start:end-start);if(part.empty()||part=="."||part=="..")return false;if(end==std::string_view::npos)break;start=end+1;}return true;}
std::vector<std::byte> read_bytes(const std::filesystem::path& path,std::uint64_t maximum){std::error_code error;const auto status=std::filesystem::symlink_status(path,error);if(error||!std::filesystem::is_regular_file(status)||std::filesystem::is_symlink(status))throw std::runtime_error("visual input must be a regular non-symlink file: "+path.string());const auto size=std::filesystem::file_size(path,error);if(error||size==0||size>maximum||size>std::numeric_limits<std::size_t>::max())throw std::runtime_error("visual input is empty or exceeds byte limit: "+path.string());std::vector<std::byte> bytes(static_cast<std::size_t>(size));std::ifstream input(path,std::ios::binary);if(!input||!input.read(reinterpret_cast<char*>(bytes.data()),static_cast<std::streamsize>(bytes.size())))throw std::runtime_error("cannot read complete visual input: "+path.string());return bytes;}
void reject_symlink_components(const std::filesystem::path& root,const std::filesystem::path& relative){auto current=root;for(const auto&part:relative){current/=part;std::error_code error;const auto status=std::filesystem::symlink_status(current,error);if(error||std::filesystem::is_symlink(status))throw std::runtime_error("visual input path is absent or traverses a symlink: "+relative.generic_string());}}
}

AuthoredVisualSet load_authored_visual_set(const std::filesystem::path& manifest_path,const VisualSetLimits& limits){
  if(limits.max_manifest_bytes==0||limits.max_total_encoded_bytes==0||limits.max_total_decoded_bytes==0||limits.max_frames==0||limits.max_frames>4096||limits.max_channel_maps>24576)throw std::invalid_argument("visual-set limits are invalid");
  const auto manifest_bytes=read_bytes(manifest_path,limits.max_manifest_bytes);const std::string source(reinterpret_cast<const char*>(manifest_bytes.data()),manifest_bytes.size());AuthoredVisualSet result;std::map<std::string,bool> seen;std::vector<std::vector<std::string>> definitions,map_definitions;std::istringstream stream(source);std::string line;std::size_t line_number=0;
  while(std::getline(stream,line)){if(++line_number>8192)throw std::runtime_error("visual-set manifest exceeds line limit");line=trim(line);if(line.empty()||line.starts_with('#'))continue;const auto equals=line.find('=');if(equals==std::string::npos)throw std::runtime_error("visual-set line "+std::to_string(line_number)+" requires key=value");const auto key=trim(line.substr(0,equals));const auto value=trim(line.substr(equals+1));if(key!="frame"&&key!="map"&&key!="layer"&&!seen.emplace(key,true).second)throw std::runtime_error("duplicate visual-set field: "+key);if(key=="schema")result.schema=value;else if(key=="rights"){if(value!="ORIGINAL_USER_CREATION")throw std::runtime_error("the initial visual-set schema admits only ORIGINAL_USER_CREATION");}else if(key=="max_width")result.sheet.maximum_width=u32(value,key);else if(key=="max_height")result.sheet.maximum_height=u32(value,key);else if(key=="padding")result.sheet.padding=u32(value,key);else if(key=="trim")result.sheet.trim_frames=boolean(value,key);else if(key=="alpha_threshold"){const auto parsed=u32(value,key);if(parsed>255)throw std::runtime_error("alpha threshold exceeds 255");result.sheet.alpha_threshold=static_cast<std::uint8_t>(parsed);}else if(key=="pixel_art")result.pixel_art=boolean(value,key);else if(key=="grid_width")result.pixel_policy.grid_width=u32(value,key);else if(key=="grid_height")result.pixel_policy.grid_height=u32(value,key);else if(key=="maximum_colors")result.pixel_policy.maximum_colors=u32(value,key);else if(key=="binary_alpha")result.pixel_policy.binary_alpha=boolean(value,key);else if(key=="temporal_max_changed_per_million")result.temporal_max_changed_per_million=u32(value,key);else if(key=="temporal_min_silhouette_iou_per_million")result.temporal_min_silhouette_iou_per_million=u32(value,key);else if(key=="layer"){if(!token(value)||result.layer_order.size()>=64||std::ranges::find(result.layer_order,value)!=result.layer_order.end())throw std::runtime_error("visual-set layer is invalid or duplicate");result.layer_order.push_back(value);}else if(key=="frame"){if(definitions.size()>=limits.max_frames)throw std::runtime_error("visual-set frame count exceeds limit");definitions.push_back(split(value,'|'));}else if(key=="map"){if(map_definitions.size()>=limits.max_channel_maps)throw std::runtime_error("visual-set channel-map count exceeds limit");map_definitions.push_back(split(value,'|'));}else throw std::runtime_error("unknown visual-set field: "+key);}
  if(result.schema!="gspl.visual-set/0.1"||!seen.contains("rights")||!seen.contains("max_width")||!seen.contains("max_height")||!seen.contains("padding")||!seen.contains("trim")||!seen.contains("alpha_threshold")||!seen.contains("pixel_art")||!seen.contains("grid_width")||!seen.contains("grid_height")||!seen.contains("maximum_colors")||!seen.contains("binary_alpha")||!seen.contains("temporal_max_changed_per_million")||!seen.contains("temporal_min_silhouette_iou_per_million")||result.temporal_max_changed_per_million>1'000'000||result.temporal_min_silhouette_iou_per_million>1'000'000||result.layer_order.empty()||definitions.empty())throw std::runtime_error("visual-set manifest is incomplete or uses an unsupported schema/policy");
  const auto root=manifest_path.parent_path();std::set<std::string> ids;std::uint64_t total_encoded=0,total_decoded=0;
  for(const auto&parts:definitions){if(parts.size()!=8)throw std::runtime_error("frame requires animation|direction|layer|ordinal|path|pivot_x|pivot_y|duration");if(!token(parts[0])||!token(parts[2])||std::ranges::find(result.layer_order,parts[2])==result.layer_order.end())throw std::runtime_error("frame animation or declared layer token is invalid");const auto parsed_direction=parse_direction(parts[1]);const auto ordinal=u32(parts[3],"frame.ordinal");if(ordinal>9999)throw std::runtime_error("frame ordinal exceeds 9999");if(!safe_path(parts[4]))throw std::runtime_error("frame path is unsafe");std::ostringstream id;id<<parts[0]<<'.'<<parts[1]<<'.'<<parts[2]<<'.'<<std::setw(4)<<std::setfill('0')<<ordinal;if(!ids.insert(id.str()).second)throw std::runtime_error("duplicate semantic frame identity: "+id.str());const std::filesystem::path relative=std::filesystem::path(parts[4]);reject_symlink_components(root,relative);const auto encoded=read_bytes(root/relative,limits.image.max_input_bytes);if(encoded.size()>limits.max_total_encoded_bytes-total_encoded)throw std::runtime_error("visual-set encoded inputs exceed aggregate byte limit");total_encoded+=encoded.size();auto image=decode_png(encoded,limits.image);if(image.pixels.size()>limits.max_total_decoded_bytes-total_decoded)throw std::runtime_error("visual-set decoded inputs exceed aggregate byte limit");total_decoded+=image.pixels.size();if(image.color_space==ColorSpace::unknown)throw std::runtime_error("visual-set PNG requires an explicit sRGB chunk: "+parts[4]);result.frames.push_back({id.str(),std::move(image),i32(parts[5],"frame.pivot_x"),i32(parts[6],"frame.pivot_y"),u32(parts[7],"frame.duration"),{}});if(result.frames.back().duration_ticks==0)throw std::runtime_error("frame duration must be positive");result.semantics.push_back({parts[0],parsed_direction,parts[2],ordinal,id.str()});}
  for(const auto&parts:map_definitions){if(parts.size()!=6)throw std::runtime_error("map requires kind|animation|direction|layer|ordinal|path");const auto kind=parse_map_kind(parts[0]);if(!token(parts[1])||!token(parts[3])||std::ranges::find(result.layer_order,parts[3])==result.layer_order.end())throw std::runtime_error("channel-map target semantics are invalid");(void)parse_direction(parts[2]);const auto ordinal=u32(parts[4],"map.ordinal");if(ordinal>9999||!safe_path(parts[5]))throw std::runtime_error("channel-map ordinal or path is invalid");std::ostringstream target_id;target_id<<parts[1]<<'.'<<parts[2]<<'.'<<parts[3]<<'.'<<std::setw(4)<<std::setfill('0')<<ordinal;const auto target=std::ranges::find(result.frames,target_id.str(),&FrameSource::id);if(target==result.frames.end())throw std::runtime_error("channel map references an absent semantic frame: "+target_id.str());const std::filesystem::path relative=std::filesystem::path(parts[5]);reject_symlink_components(root,relative);const auto encoded=read_bytes(root/relative,limits.image.max_input_bytes);if(encoded.size()>limits.max_total_encoded_bytes-total_encoded)throw std::runtime_error("visual-set encoded inputs exceed aggregate byte limit");total_encoded+=encoded.size();auto image=decode_png(encoded,limits.image);if(image.pixels.size()>limits.max_total_decoded_bytes-total_decoded)throw std::runtime_error("visual-set decoded inputs exceed aggregate byte limit");total_decoded+=image.pixels.size();if(kind==ChannelMapKind::emissive){if(image.color_space!=ColorSpace::srgb)throw std::runtime_error("emissive channel maps require an explicit sRGB chunk");}else{if(image.color_space!=ColorSpace::unknown)throw std::runtime_error("non-color channel maps must not carry an sRGB chunk");image.color_space=ColorSpace::data;}ChannelMap map{target_id.str()+'.'+std::string(map_kind_text(kind)),target_id.str(),kind,std::move(image)};const auto validation=validate_channel_map(map,*target);if(!validation.ok())throw std::runtime_error(validation.diagnostics.front().code+": "+validation.diagnostics.front().message);result.channel_maps.push_back(std::move(map));}
  result.canonical_channel_metadata=canonicalize_channel_maps(result.channel_maps);
  std::map<std::tuple<std::string,Direction2d,std::uint32_t>,std::vector<std::size_t>> stacks;std::map<std::pair<std::string,Direction2d>,std::set<std::uint32_t>> sequences;for(std::size_t i=0;i<result.semantics.size();++i){const auto&s=result.semantics[i];stacks[{s.animation,s.direction,s.ordinal}].push_back(i);sequences[{s.animation,s.direction}].insert(s.ordinal);}
  for(const auto&[key,indexes]:stacks){static_cast<void>(key);if(indexes.size()!=result.layer_order.size())throw std::runtime_error("each visual frame must provide every declared layer exactly once");std::set<std::string_view> layers;const auto&reference=result.frames[indexes.front()];for(const auto index:indexes){layers.insert(result.semantics[index].layer);const auto&frame=result.frames[index];if(frame.image.width!=reference.image.width||frame.image.height!=reference.image.height||frame.pivot_x!=reference.pivot_x||frame.pivot_y!=reference.pivot_y||frame.duration_ticks!=reference.duration_ticks)throw std::runtime_error("layers in a visual frame must share canvas, pivot, and duration");}if(layers.size()!=result.layer_order.size())throw std::runtime_error("visual frame layer stack is duplicate or incomplete");}
  for(const auto&[key,ordinals]:sequences){static_cast<void>(key);std::uint32_t expected=0;for(const auto ordinal:ordinals)if(ordinal!=expected++)throw std::runtime_error("animation ordinals must be contiguous and start at zero");}
  if(result.pixel_art){std::set<std::uint32_t> global_palette;for(const auto&frame:result.frames){const auto validation=validate_pixel_art(frame.image,result.pixel_policy);if(!validation.ok())throw std::runtime_error(validation.diagnostics.front().code+": "+validation.diagnostics.front().message);for(const auto&entry:extract_palette(frame.image,result.pixel_policy.maximum_colors+1))global_palette.insert(entry.rgba);}if(global_palette.size()>result.pixel_policy.maximum_colors)throw std::runtime_error("visual-set frames do not share the declared fixed palette budget");}
  std::map<std::tuple<std::string,Direction2d,std::string>,std::vector<std::pair<std::uint32_t,std::size_t>>> temporal_sequences;for(std::size_t i=0;i<result.semantics.size();++i){const auto&s=result.semantics[i];temporal_sequences[{s.animation,s.direction,s.layer}].push_back({s.ordinal,i});}for(auto&[key,sequence]:temporal_sequences){static_cast<void>(key);if(sequence.size()<2)continue;std::ranges::sort(sequence);std::vector<FrameSource> ordered;ordered.reserve(sequence.size());for(const auto&[ordinal,index]:sequence){static_cast<void>(ordinal);ordered.push_back(result.frames[index]);}auto metrics=analyze_temporal_stability(ordered,result.sheet.alpha_threshold);for(const auto&metric:metrics)if(metric.changed_per_million>result.temporal_max_changed_per_million||metric.silhouette_iou_per_million<result.temporal_min_silhouette_iou_per_million)throw std::runtime_error("visual-set temporal stability policy failed between "+metric.from_frame+" and "+metric.to_frame);result.temporal_metrics.insert(result.temporal_metrics.end(),metrics.begin(),metrics.end());}
  std::vector<std::size_t> order(result.semantics.size());std::iota(order.begin(),order.end(),0);std::ranges::sort(order,[&](auto left,auto right){const auto&a=result.semantics[left];const auto&b=result.semantics[right];const auto al=std::ranges::find(result.layer_order,a.layer)-result.layer_order.begin();const auto bl=std::ranges::find(result.layer_order,b.layer)-result.layer_order.begin();return std::tuple{a.animation,a.direction,a.ordinal,al}<std::tuple{b.animation,b.direction,b.ordinal,bl};});std::ranges::sort(result.temporal_metrics,{},[](const auto&metric){return std::tuple{metric.from_frame,metric.to_frame};});std::ostringstream metadata;metadata<<"{\"frames\":[";for(std::size_t n=0;n<order.size();++n){if(n)metadata<<',';const auto&s=result.semantics[order[n]];metadata<<"{\"animation\":\""<<s.animation<<"\",\"direction\":\""<<direction_text(s.direction)<<"\",\"frameId\":\""<<s.frame_id<<"\",\"layer\":\""<<s.layer<<"\",\"ordinal\":"<<s.ordinal<<'}';}metadata<<"],\"layers\":[";for(std::size_t i=0;i<result.layer_order.size();++i){if(i)metadata<<',';metadata<<'\"'<<result.layer_order[i]<<'\"';}metadata<<"],\"pixelArt\":"<<(result.pixel_art?"true":"false")<<",\"schema\":\"gspl.visual-projection/0.1\",\"temporalTransitions\":[";for(std::size_t i=0;i<result.temporal_metrics.size();++i){if(i)metadata<<',';const auto&m=result.temporal_metrics[i];metadata<<"{\"changedPerMillion\":"<<m.changed_per_million<<",\"from\":\""<<m.from_frame<<"\",\"silhouetteIouPerMillion\":"<<m.silhouette_iou_per_million<<",\"to\":\""<<m.to_frame<<"\"}";}metadata<<"]}";result.canonical_metadata=metadata.str();
  (void)compile_sprite_sheet(result.frames,result.sheet);return result;
}
} // namespace gspl::sprites
