#include "gspl_sprites/visual_set.hpp"

#include <algorithm>
#include <array>
#include <charconv>
#include <fstream>
#include <iomanip>
#include <limits>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>

namespace gspl::sprites {
namespace {
std::string trim(std::string value){const auto first=value.find_first_not_of(" \t\r\n");if(first==std::string::npos)return{};return value.substr(first,value.find_last_not_of(" \t\r\n")-first+1);}
std::vector<std::string> split(std::string_view value,char delimiter){std::vector<std::string> result;std::size_t start=0;while(start<=value.size()){const auto end=value.find(delimiter,start);result.emplace_back(value.substr(start,end==std::string_view::npos?value.size()-start:end-start));if(end==std::string_view::npos)break;start=end+1;}return result;}
std::uint32_t u32(std::string_view value,std::string_view field){std::uint32_t output{};const auto[end,error]=std::from_chars(value.data(),value.data()+value.size(),output);if(error!=std::errc{}||end!=value.data()+value.size())throw std::runtime_error("invalid unsigned integer for "+std::string(field));return output;}
std::int32_t i32(std::string_view value,std::string_view field){std::int32_t output{};const auto[end,error]=std::from_chars(value.data(),value.data()+value.size(),output);if(error!=std::errc{}||end!=value.data()+value.size())throw std::runtime_error("invalid signed integer for "+std::string(field));return output;}
bool boolean(std::string_view value,std::string_view field){if(value=="true")return true;if(value=="false")return false;throw std::runtime_error("invalid boolean for "+std::string(field));}
bool token(std::string_view value){return!value.empty()&&value.size()<=64&&std::ranges::all_of(value,[](unsigned char c){return(c>='a'&&c<='z')||(c>='0'&&c<='9')||c=='_'||c=='-';});}
bool direction(std::string_view value){static constexpr std::array values{"none","north","north_east","east","south_east","south","south_west","west","north_west"};return std::ranges::find(values,value)!=values.end();}
bool safe_path(std::string_view value){if(value.empty()||value.size()>1024||value.front()=='/'||value.back()=='/'||value.find('\\')!=std::string_view::npos||value.find(':')!=std::string_view::npos||!std::ranges::all_of(value,[](unsigned char c){return c>=0x20&&c<0x7f;}))return false;std::size_t start=0;while(start<value.size()){const auto end=value.find('/',start);const auto part=value.substr(start,end==std::string_view::npos?value.size()-start:end-start);if(part.empty()||part=="."||part=="..")return false;if(end==std::string_view::npos)break;start=end+1;}return true;}
std::vector<std::byte> read_bytes(const std::filesystem::path& path,std::uint64_t maximum){std::error_code error;const auto status=std::filesystem::symlink_status(path,error);if(error||!std::filesystem::is_regular_file(status)||std::filesystem::is_symlink(status))throw std::runtime_error("visual input must be a regular non-symlink file: "+path.string());const auto size=std::filesystem::file_size(path,error);if(error||size==0||size>maximum||size>std::numeric_limits<std::size_t>::max())throw std::runtime_error("visual input is empty or exceeds byte limit: "+path.string());std::vector<std::byte> bytes(static_cast<std::size_t>(size));std::ifstream input(path,std::ios::binary);if(!input||!input.read(reinterpret_cast<char*>(bytes.data()),static_cast<std::streamsize>(bytes.size())))throw std::runtime_error("cannot read complete visual input: "+path.string());return bytes;}
void reject_symlink_components(const std::filesystem::path& root,const std::filesystem::path& relative){auto current=root;for(const auto&part:relative){current/=part;std::error_code error;const auto status=std::filesystem::symlink_status(current,error);if(error||std::filesystem::is_symlink(status))throw std::runtime_error("visual input path is absent or traverses a symlink: "+relative.generic_string());}}
}

AuthoredVisualSet load_authored_visual_set(const std::filesystem::path& manifest_path,const VisualSetLimits& limits){
  if(limits.max_manifest_bytes==0||limits.max_total_encoded_bytes==0||limits.max_total_decoded_bytes==0||limits.max_frames==0||limits.max_frames>4096)throw std::invalid_argument("visual-set limits are invalid");const auto manifest_bytes=read_bytes(manifest_path,limits.max_manifest_bytes);const std::string source(reinterpret_cast<const char*>(manifest_bytes.data()),manifest_bytes.size());AuthoredVisualSet result;std::map<std::string,bool> seen;std::vector<std::vector<std::string>> definitions;std::istringstream stream(source);std::string line;std::size_t line_number=0;
  while(std::getline(stream,line)){if(++line_number>8192)throw std::runtime_error("visual-set manifest exceeds line limit");line=trim(line);if(line.empty()||line.starts_with('#'))continue;const auto equals=line.find('=');if(equals==std::string::npos)throw std::runtime_error("visual-set line "+std::to_string(line_number)+" requires key=value");const auto key=trim(line.substr(0,equals));const auto value=trim(line.substr(equals+1));if(key!="frame"&&!seen.emplace(key,true).second)throw std::runtime_error("duplicate visual-set field: "+key);if(key=="schema")result.schema=value;else if(key=="rights"){if(value!="ORIGINAL_USER_CREATION")throw std::runtime_error("the initial visual-set schema admits only ORIGINAL_USER_CREATION");}else if(key=="max_width")result.sheet.maximum_width=u32(value,key);else if(key=="max_height")result.sheet.maximum_height=u32(value,key);else if(key=="padding")result.sheet.padding=u32(value,key);else if(key=="trim")result.sheet.trim_frames=boolean(value,key);else if(key=="alpha_threshold"){const auto parsed=u32(value,key);if(parsed>255)throw std::runtime_error("alpha threshold exceeds 255");result.sheet.alpha_threshold=static_cast<std::uint8_t>(parsed);}else if(key=="frame"){if(definitions.size()>=limits.max_frames)throw std::runtime_error("visual-set frame count exceeds limit");definitions.push_back(split(value,'|'));}else throw std::runtime_error("unknown visual-set field: "+key);}
  if(result.schema!="gspl.visual-set/0.1"||!seen.contains("rights")||!seen.contains("max_width")||!seen.contains("max_height")||!seen.contains("padding")||!seen.contains("trim")||!seen.contains("alpha_threshold")||definitions.empty())throw std::runtime_error("visual-set manifest is incomplete or uses an unsupported schema");
  const auto root=manifest_path.parent_path();std::set<std::string> ids;std::uint64_t total_encoded=0,total_decoded=0;
  for(const auto&parts:definitions){if(parts.size()!=8)throw std::runtime_error("frame requires animation|direction|layer|ordinal|path|pivot_x|pivot_y|duration");if(!token(parts[0])||!direction(parts[1])||!token(parts[2]))throw std::runtime_error("frame animation, direction, or layer token is invalid");const auto ordinal=u32(parts[3],"frame.ordinal");if(ordinal>9999)throw std::runtime_error("frame ordinal exceeds 9999");if(!safe_path(parts[4]))throw std::runtime_error("frame path is unsafe");std::ostringstream id;id<<parts[0]<<'.'<<parts[1]<<'.'<<parts[2]<<'.'<<std::setw(4)<<std::setfill('0')<<ordinal;if(!ids.insert(id.str()).second)throw std::runtime_error("duplicate semantic frame identity: "+id.str());const std::filesystem::path relative=std::filesystem::path(parts[4]);reject_symlink_components(root,relative);const auto encoded=read_bytes(root/relative,limits.image.max_input_bytes);if(encoded.size()>limits.max_total_encoded_bytes-total_encoded)throw std::runtime_error("visual-set encoded inputs exceed aggregate byte limit");total_encoded+=encoded.size();auto image=decode_png(encoded,limits.image);if(image.pixels.size()>limits.max_total_decoded_bytes-total_decoded)throw std::runtime_error("visual-set decoded inputs exceed aggregate byte limit");total_decoded+=image.pixels.size();if(image.color_space==ColorSpace::unknown)throw std::runtime_error("visual-set PNG requires an explicit sRGB chunk: "+parts[4]);result.frames.push_back({id.str(),std::move(image),i32(parts[5],"frame.pivot_x"),i32(parts[6],"frame.pivot_y"),u32(parts[7],"frame.duration")});if(result.frames.back().duration_ticks==0)throw std::runtime_error("frame duration must be positive");}
  (void)compile_sprite_sheet(result.frames,result.sheet);return result;
}
} // namespace gspl::sprites
